name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      pocketbase: ${{ steps.pocketbase.outputs.result }}
      package: ${{ steps.package.outputs.result }}
    steps:
      - name: Get latest pocketbase release
        id: pocketbase
        uses: actions/github-script@v7
        env:
          OWNER: pocketbase
          REPO: pocketbase
          EXCLUDES: '["draft", "prerelease"]'
        with:
          result-encoding: string
          script: |
            const {OWNER,REPO,EXCLUDES} = process.env;
            const {data} = await github.rest.repos.listReleases({
              owner: OWNER,
              repo: REPO
            })

            const releases = data.filter(release => JSON.parse(EXCLUDES).every(exclude => !release[exclude]))
            const latest = releases[0]

            return latest.tag_name.replace('v','')

      - name: Get latest package version
        id: package
        uses: actions/github-script@v7
        env:
          PACKAGE_NAME: pocketbase
          PACKAGE_TYPE: container
        with:
          result-encoding: string
          script: |
            const {PACKAGE_NAME,PACKAGE_TYPE} = process.env;
            const {data: packages} = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
              org: context.repo.owner,
              package_type: PACKAGE_TYPE,
              package_name: PACKAGE_NAME,
            })

            const latest = packages.filter((p) =>
              p.metadata.container.tags.includes("latest")
            )[0];

            return latest.metadata.container.tags.find((v) => /^v?\d+\.\d+\.\d+$/.test(v)) || '0.0.0'

  build:
    runs-on: ubuntu-latest
    needs: check
    if: (needs.check.outputs.pocketbase != needs.check.outputs.package) || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io
          # Username used to log against the Docker registry
          username: butlerba
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Get version from needs or input
        id: version
        run: echo "value=${{ github.event.inputs.version || needs.check.outputs.pocketbase }}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Build the Docker image
        run: docker buildx build . --file DockerFile --args VERSION=${{ steps.version.outputs.value }} --tag ghcr.io/butlerba/thwip-pocketbase:latest --push
